language: go

go:
- 1.20.x
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
before_script:
 - go get github.com/golang/mock/mockgen
 - go get ./...
 - go generate ./...
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)