// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recording.proto

package rapv1

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumLifeType int32

const (
	EnumLifeType_START   EnumLifeType = 0
	EnumLifeType_ENABLE  EnumLifeType = 1
	EnumLifeType_DISABLE EnumLifeType = 2
	EnumLifeType_DESTROY EnumLifeType = 3
)

var EnumLifeType_name = map[int32]string{
	0: "START",
	1: "ENABLE",
	2: "DISABLE",
	3: "DESTROY",
}

var EnumLifeType_value = map[string]int32{
	"START":   0,
	"ENABLE":  1,
	"DISABLE": 2,
	"DESTROY": 3,
}

func (x EnumLifeType) String() string {
	return proto.EnumName(EnumLifeType_name, int32(x))
}

func (EnumLifeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{0}
}

type Recording struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metadata             map[string]string     `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Subjects             []*SubjectRecording   `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	CustomEvents         []*CustomEventCapture `protobuf:"bytes,4,rep,name=customEvents,proto3" json:"customEvents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Recording) Reset()         { *m = Recording{} }
func (m *Recording) String() string { return proto.CompactTextString(m) }
func (*Recording) ProtoMessage()    {}
func (*Recording) Descriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{0}
}

func (m *Recording) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recording.Unmarshal(m, b)
}

func (m *Recording) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recording.Marshal(b, m, deterministic)
}

func (m *Recording) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recording.Merge(m, src)
}

func (m *Recording) XXX_Size() int {
	return xxx_messageInfo_Recording.Size(m)
}

func (m *Recording) XXX_DiscardUnknown() {
	xxx_messageInfo_Recording.DiscardUnknown(m)
}

var xxx_messageInfo_Recording proto.InternalMessageInfo

func (m *Recording) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recording) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Recording) GetSubjects() []*SubjectRecording {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *Recording) GetCustomEvents() []*CustomEventCapture {
	if m != nil {
		return m.CustomEvents
	}
	return nil
}

type SubjectRecording struct {
	Id                   int32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata             map[string]string        `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomEvents         []*CustomEventCapture    `protobuf:"bytes,4,rep,name=customEvents,proto3" json:"customEvents,omitempty"`
	LifecycleEvents      []*LifeCycleEventCapture `protobuf:"bytes,5,rep,name=lifecycleEvents,proto3" json:"lifecycleEvents,omitempty"`
	CapturedPositions    []*VectorCapture         `protobuf:"bytes,6,rep,name=capturedPositions,proto3" json:"capturedPositions,omitempty"`
	CapturedRotations    []*VectorCapture         `protobuf:"bytes,7,rep,name=capturedRotations,proto3" json:"capturedRotations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SubjectRecording) Reset()         { *m = SubjectRecording{} }
func (m *SubjectRecording) String() string { return proto.CompactTextString(m) }
func (*SubjectRecording) ProtoMessage()    {}
func (*SubjectRecording) Descriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{1}
}

func (m *SubjectRecording) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubjectRecording.Unmarshal(m, b)
}

func (m *SubjectRecording) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubjectRecording.Marshal(b, m, deterministic)
}

func (m *SubjectRecording) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubjectRecording.Merge(m, src)
}

func (m *SubjectRecording) XXX_Size() int {
	return xxx_messageInfo_SubjectRecording.Size(m)
}

func (m *SubjectRecording) XXX_DiscardUnknown() {
	xxx_messageInfo_SubjectRecording.DiscardUnknown(m)
}

var xxx_messageInfo_SubjectRecording proto.InternalMessageInfo

func (m *SubjectRecording) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubjectRecording) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SubjectRecording) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SubjectRecording) GetCustomEvents() []*CustomEventCapture {
	if m != nil {
		return m.CustomEvents
	}
	return nil
}

func (m *SubjectRecording) GetLifecycleEvents() []*LifeCycleEventCapture {
	if m != nil {
		return m.LifecycleEvents
	}
	return nil
}

func (m *SubjectRecording) GetCapturedPositions() []*VectorCapture {
	if m != nil {
		return m.CapturedPositions
	}
	return nil
}

func (m *SubjectRecording) GetCapturedRotations() []*VectorCapture {
	if m != nil {
		return m.CapturedRotations
	}
	return nil
}

type CustomEventCapture struct {
	Time                 float32           `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Contents             string            `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CustomEventCapture) Reset()         { *m = CustomEventCapture{} }
func (m *CustomEventCapture) String() string { return proto.CompactTextString(m) }
func (*CustomEventCapture) ProtoMessage()    {}
func (*CustomEventCapture) Descriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{2}
}

func (m *CustomEventCapture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomEventCapture.Unmarshal(m, b)
}

func (m *CustomEventCapture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomEventCapture.Marshal(b, m, deterministic)
}

func (m *CustomEventCapture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomEventCapture.Merge(m, src)
}

func (m *CustomEventCapture) XXX_Size() int {
	return xxx_messageInfo_CustomEventCapture.Size(m)
}

func (m *CustomEventCapture) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomEventCapture.DiscardUnknown(m)
}

var xxx_messageInfo_CustomEventCapture proto.InternalMessageInfo

func (m *CustomEventCapture) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CustomEventCapture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomEventCapture) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *CustomEventCapture) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type LifeCycleEventCapture struct {
	Time                 float32      `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	Type                 EnumLifeType `protobuf:"varint,2,opt,name=type,proto3,enum=EnumLifeType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LifeCycleEventCapture) Reset()         { *m = LifeCycleEventCapture{} }
func (m *LifeCycleEventCapture) String() string { return proto.CompactTextString(m) }
func (*LifeCycleEventCapture) ProtoMessage()    {}
func (*LifeCycleEventCapture) Descriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{3}
}

func (m *LifeCycleEventCapture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifeCycleEventCapture.Unmarshal(m, b)
}

func (m *LifeCycleEventCapture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifeCycleEventCapture.Marshal(b, m, deterministic)
}

func (m *LifeCycleEventCapture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifeCycleEventCapture.Merge(m, src)
}

func (m *LifeCycleEventCapture) XXX_Size() int {
	return xxx_messageInfo_LifeCycleEventCapture.Size(m)
}

func (m *LifeCycleEventCapture) XXX_DiscardUnknown() {
	xxx_messageInfo_LifeCycleEventCapture.DiscardUnknown(m)
}

var xxx_messageInfo_LifeCycleEventCapture proto.InternalMessageInfo

func (m *LifeCycleEventCapture) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LifeCycleEventCapture) GetType() EnumLifeType {
	if m != nil {
		return m.Type
	}
	return EnumLifeType_START
}

type VectorCapture struct {
	Time                 float32  `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorCapture) Reset()         { *m = VectorCapture{} }
func (m *VectorCapture) String() string { return proto.CompactTextString(m) }
func (*VectorCapture) ProtoMessage()    {}
func (*VectorCapture) Descriptor() ([]byte, []int) {
	return fileDescriptor_63603908395817d1, []int{4}
}

func (m *VectorCapture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorCapture.Unmarshal(m, b)
}

func (m *VectorCapture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorCapture.Marshal(b, m, deterministic)
}

func (m *VectorCapture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorCapture.Merge(m, src)
}

func (m *VectorCapture) XXX_Size() int {
	return xxx_messageInfo_VectorCapture.Size(m)
}

func (m *VectorCapture) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorCapture.DiscardUnknown(m)
}

var xxx_messageInfo_VectorCapture proto.InternalMessageInfo

func (m *VectorCapture) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *VectorCapture) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *VectorCapture) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *VectorCapture) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterEnum("EnumLifeType", EnumLifeType_name, EnumLifeType_value)
	proto.RegisterType((*Recording)(nil), "Recording")
	proto.RegisterMapType((map[string]string)(nil), "Recording.MetadataEntry")
	proto.RegisterType((*SubjectRecording)(nil), "SubjectRecording")
	proto.RegisterMapType((map[string]string)(nil), "SubjectRecording.MetadataEntry")
	proto.RegisterType((*CustomEventCapture)(nil), "CustomEventCapture")
	proto.RegisterMapType((map[string]string)(nil), "CustomEventCapture.DataEntry")
	proto.RegisterType((*LifeCycleEventCapture)(nil), "LifeCycleEventCapture")
	proto.RegisterType((*VectorCapture)(nil), "VectorCapture")
}

func init() { proto.RegisterFile("recording.proto", fileDescriptor_63603908395817d1) }

var fileDescriptor_63603908395817d1 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xb1, 0x93, 0x76, 0xed, 0x59, 0xdb, 0x65, 0xe6, 0x8f, 0xa2, 0x4a, 0x88, 0xd1, 0xab,
	0x09, 0x09, 0x4b, 0x0c, 0xa4, 0x21, 0x86, 0x04, 0xa3, 0xcd, 0x05, 0xd2, 0x36, 0x90, 0x5b, 0x21,
	0x71, 0x99, 0x25, 0x1e, 0x0a, 0xb4, 0x71, 0x95, 0x38, 0xd3, 0xb2, 0x17, 0xe2, 0x45, 0x78, 0x2a,
	0xae, 0x50, 0x8e, 0x5b, 0xd3, 0xae, 0x81, 0x8b, 0xed, 0xce, 0xe7, 0xf8, 0xfb, 0x9d, 0xfa, 0x7c,
	0x5f, 0x15, 0xd8, 0xc9, 0x64, 0xa4, 0xb2, 0x38, 0x49, 0xbf, 0xf1, 0x79, 0xa6, 0xb4, 0x1a, 0xfc,
	0x26, 0xd0, 0x16, 0xcb, 0x1e, 0x63, 0xe0, 0xa6, 0xe1, 0x4c, 0xfa, 0x64, 0x8f, 0xec, 0xb7, 0x05,
	0x9e, 0xd9, 0x2b, 0x68, 0xcd, 0xa4, 0x0e, 0xe3, 0x50, 0x87, 0x3e, 0xdd, 0x73, 0xf6, 0xb7, 0x0f,
	0x7c, 0x6e, 0x09, 0x7e, 0xba, 0xb8, 0x0a, 0x52, 0x9d, 0x95, 0xc2, 0x2a, 0xd9, 0x73, 0x68, 0xe5,
	0xc5, 0xf9, 0x77, 0x19, 0xe9, 0xdc, 0x77, 0x90, 0xda, 0xe5, 0x63, 0xd3, 0xb0, 0xb0, 0xb0, 0x12,
	0x76, 0x08, 0x9d, 0xa8, 0xc8, 0xb5, 0x9a, 0x05, 0x97, 0x32, 0xd5, 0xb9, 0xef, 0x22, 0x72, 0x9f,
	0x0f, 0xff, 0x36, 0x87, 0xe1, 0x5c, 0x17, 0x99, 0x14, 0x6b, 0xc2, 0xfe, 0x11, 0x74, 0xd7, 0x9e,
	0xc0, 0x3c, 0x70, 0x7e, 0xc8, 0x72, 0xb1, 0x41, 0x75, 0x64, 0x0f, 0xa0, 0x71, 0x19, 0x4e, 0x0b,
	0xe9, 0x53, 0xec, 0x99, 0xe2, 0x0d, 0x7d, 0x4d, 0x06, 0x3f, 0x1d, 0xf0, 0x6e, 0x3e, 0x8a, 0xf5,
	0x80, 0x26, 0x31, 0xf2, 0x0d, 0x41, 0x93, 0xd8, 0x7a, 0x42, 0x57, 0x3c, 0x39, 0x5a, 0xf1, 0xc4,
	0x6c, 0xf7, 0x64, 0x63, 0xbb, 0x7f, 0x5a, 0x73, 0xdb, 0x5d, 0xd9, 0x7b, 0xd8, 0x99, 0x26, 0x17,
	0x32, 0x2a, 0xa3, 0xa9, 0x5c, 0xb0, 0x0d, 0x64, 0x1f, 0xf1, 0x93, 0xe4, 0x42, 0x0e, 0x6d, 0x7f,
	0x89, 0xdf, 0x94, 0xb3, 0xb7, 0xb0, 0x1b, 0x99, 0xbb, 0xf8, 0xb3, 0xca, 0x13, 0x9d, 0xa8, 0x34,
	0xf7, 0x9b, 0x38, 0xa3, 0xc7, 0xbf, 0xc8, 0x48, 0xab, 0x6c, 0xc9, 0x6e, 0x0a, 0x57, 0x69, 0xa1,
	0x74, 0x68, 0xe8, 0xad, 0xff, 0xd3, 0x56, 0x78, 0xb7, 0xa4, 0x7e, 0x11, 0x60, 0x9b, 0xfe, 0x54,
	0xd9, 0xe8, 0x64, 0xf1, 0x7f, 0xa5, 0x02, 0xcf, 0xb5, 0x79, 0xf5, 0xa1, 0x15, 0xa9, 0x54, 0xa3,
	0x65, 0x0e, 0xf6, 0x6d, 0xcd, 0x5e, 0x80, 0x8b, 0x39, 0x9a, 0x18, 0x1e, 0xd7, 0xc4, 0xc0, 0x47,
	0x36, 0x45, 0x94, 0xf6, 0x0f, 0xa1, 0x3d, 0xba, 0xd5, 0x1a, 0x67, 0xf0, 0xb0, 0x36, 0xa9, 0xda,
	0x45, 0x9e, 0x82, 0xab, 0xcb, 0xb9, 0x99, 0xd2, 0x3b, 0xe8, 0xf2, 0x20, 0x2d, 0x66, 0x15, 0x3d,
	0x29, 0xe7, 0x52, 0xe0, 0xd5, 0xe0, 0x14, 0xba, 0x6b, 0xbe, 0xd7, 0xce, 0xe9, 0x00, 0xb9, 0xc2,
	0x21, 0x54, 0x90, 0xab, 0xaa, 0x2a, 0xd1, 0x03, 0x2a, 0x48, 0x59, 0x55, 0xd7, 0xbe, 0x6b, 0xaa,
	0xeb, 0x67, 0xef, 0xa0, 0xb3, 0xfa, 0x23, 0xac, 0x0d, 0x8d, 0xf1, 0xe4, 0x58, 0x4c, 0xbc, 0x7b,
	0x0c, 0xa0, 0x19, 0x9c, 0x1d, 0x7f, 0x38, 0x09, 0x3c, 0xc2, 0xb6, 0x61, 0x6b, 0xf4, 0x71, 0x8c,
	0x05, 0xc5, 0x22, 0x18, 0x4f, 0xc4, 0xa7, 0xaf, 0x9e, 0x73, 0xde, 0xc4, 0x8f, 0xca, 0xcb, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x09, 0x49, 0xc8, 0x67, 0x04, 0x00, 0x00,
}
